<?php

namespace MobileCart\HWIOAuthBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerOAuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOAuthRepository extends EntityRepository
{
}
